services:
  database:
    profiles:
      - prod
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=restaurant'
      - 'POSTGRES_PASSWORD=password'